{% set name = "protobuf-c" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/protobuf-c/protobuf-c/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f3046f94ef6f85cf4311f6c4c51e2095c381ce7bb7fd4f90ea8d9cd99fca3c04
  patches:
    # support pointing to PROTOBUF_PROTOC_EXECUTABLE via environment variable in CMAKE_CROSSCOMPILING scenarios
    - patches/0002-support-pointing-to-PROTOBUF_PROTOC_EXECUTABLE-via-e.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - libprotobuf
  host:
    - libprotobuf
    - libabseil

test:
  commands:
    - test -f ${PREFIX}/lib/libprotobuf-c${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_BIN%\protobuf-c.dll exit 1  # [win]

about:
  home: https://github.com/protobuf-c/protobuf-c
  summary: 'C API for Google Protobuf'
  description: |
    a pure C library that implements protobuf encoding and decoding
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hobu
